import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from '../components/index/About'
import "../node_modules/bootstrap/dist/css/bootstrap.min.css"

export default function Home(){
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <About/> 
    </div>
  )
}
