import { useEffect } from 'react';
import Head from 'next/head'
import Cards from '../components/Cards'
import About from '../components/index/About'
import "../node_modules/bootstrap/dist/css/bootstrap.min.css"
import AOS from 'aos';
import 'aos/dist/aos.css';

export default function Home() {
  useEffect(() => {
    AOS.init({
      offset: 200,
      delay: 0,
      duration: 600
    });

  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
      <Cards />
    </div>
  )
}
